export const Categories = [
  "None",
  "Work",
  "Education",
  "Inspiration",
  "Hobby",
  "Finance",
  "Health & Fitness",
  "News & Articles",
  "Entertainment",
  "Shopping",
  "Recipes & Cooking",
  "Personal Development",
  "Travel",
  "Tech & Gadgets",
  "Business & Startups",
  "Marketing & Growth",
  "Freelancing",
  "Books & Reading",
  "Self-Care & Mindfulness",
  "Social Media & Networking",
  "Tools & Resources",
  "Other",
];
